#   -*- coding:utf-8 -*-
#   The subwindow_pingouin.py in FeatureAnalyzer
#   created by Jiang Feng(silencejiang@zju.edu.cn)
#   created at 17:04 on 2022/4/10
#   copied form parameter_basic.py file

from PyQt5 import QtCore,QtWidgets
from ui.subwindow.myqmidsubwindow import MyQMdiSubWindow
from data import Globalvar as gl

class SubWindow_Pingouin_basic(MyQMdiSubWindow):
    count = 1
    def __init__(self):
        MyQMdiSubWindow.__init__(self)
        self.win_type = gl.get_value("Window_Pingouin")
        self.setWindowTitle(self.generate_title(SubWindow_Pingouin_basic.count))

        self.centralwidget = QtWidgets.QWidget()
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.label_window = QtWidgets.QLabel(self.centralwidget)
        self.label_window.setObjectName("label_window")
        self.gridLayout_5.addWidget(self.label_window, 0, 0, 1, 1)
        self.comboBox_window = QtWidgets.QComboBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_window.sizePolicy().hasHeightForWidth())
        self.comboBox_window.setSizePolicy(sizePolicy)
        self.comboBox_window.setMinimumSize(QtCore.QSize(300, 0))
        self.comboBox_window.setObjectName("comboBox_window")
        self.gridLayout_5.addWidget(self.comboBox_window, 0, 1, 1, 2)
        self.label_database = QtWidgets.QLabel(self.centralwidget)
        self.label_database.setObjectName("label_database")
        self.gridLayout_5.addWidget(self.label_database, 1, 0, 1, 1)
        self.comboBox_database = QtWidgets.QComboBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_database.sizePolicy().hasHeightForWidth())
        self.comboBox_database.setSizePolicy(sizePolicy)
        self.comboBox_database.setMinimumSize(QtCore.QSize(300, 0))
        self.comboBox_database.setObjectName("comboBox_database")
        self.gridLayout_5.addWidget(self.comboBox_database, 1, 1, 1, 2)
        self.pushButton_start = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_start.setMinimumSize(QtCore.QSize(100, 0))
        self.pushButton_start.setObjectName("pushButton_start")
        self.gridLayout_5.addWidget(self.pushButton_start, 1, 3, 1, 1)
        self.pushButton_help = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_help.setMinimumSize(QtCore.QSize(100, 0))
        self.pushButton_help.setObjectName("pushButton_help")
        self.gridLayout_5.addWidget(self.pushButton_help, 1, 4, 1, 1)
        self.listView_all = QtWidgets.QListView(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.listView_all.sizePolicy().hasHeightForWidth())
        self.listView_all.setSizePolicy(sizePolicy)
        self.listView_all.setMinimumSize(QtCore.QSize(200, 0))
        self.listView_all.setObjectName("listView_all")
        self.gridLayout_5.addWidget(self.listView_all, 2, 0, 5, 2)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.label_l1 = QtWidgets.QLabel(self.centralwidget)
        self.label_l1.setObjectName("label_l1")
        self.gridLayout.addWidget(self.label_l1, 0, 1, 1, 1)
        self.pushButton_1 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_1.setObjectName("pushButton_1")
        self.gridLayout.addWidget(self.pushButton_1, 1, 0, 1, 1)
        self.listView_1 = QtWidgets.QListView(self.centralwidget)
        self.listView_1.setObjectName("listView_1")
        self.gridLayout.addWidget(self.listView_1, 1, 1, 1, 1)
        self.gridLayout_5.addLayout(self.gridLayout, 2, 2, 1, 2)
        self.gridLayout_4 = QtWidgets.QGridLayout()
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.comboBox_p7 = QtWidgets.QComboBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.comboBox_p7.sizePolicy().hasHeightForWidth())
        self.comboBox_p7.setSizePolicy(sizePolicy)
        self.comboBox_p7.setObjectName("comboBox_p7")
        self.gridLayout_4.addWidget(self.comboBox_p7, 6, 1, 1, 2)
        self.lineEdit_s4 = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.lineEdit_s4.sizePolicy().hasHeightForWidth())
        self.lineEdit_s4.setSizePolicy(sizePolicy)
        self.lineEdit_s4.setObjectName("lineEdit_s4")
        self.gridLayout_4.addWidget(self.lineEdit_s4, 11, 1, 1, 2)
        self.label_p8 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.label_p8.sizePolicy().hasHeightForWidth())
        self.label_p8.setSizePolicy(sizePolicy)
        self.label_p8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_p8.setObjectName("label_p8")
        self.gridLayout_4.addWidget(self.label_p8, 7, 0, 1, 1)
        self.label_s1 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.label_s1.sizePolicy().hasHeightForWidth())
        self.label_s1.setSizePolicy(sizePolicy)
        self.label_s1.setAlignment(QtCore.Qt.AlignCenter)
        self.label_s1.setObjectName("label_s1")
        self.gridLayout_4.addWidget(self.label_s1, 8, 0, 1, 1)
        self.lineEdit_s3 = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.lineEdit_s3.sizePolicy().hasHeightForWidth())
        self.lineEdit_s3.setSizePolicy(sizePolicy)
        self.lineEdit_s3.setObjectName("lineEdit_s3")
        self.gridLayout_4.addWidget(self.lineEdit_s3, 10, 1, 1, 2)
        self.comboBox_p5 = QtWidgets.QComboBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.comboBox_p5.sizePolicy().hasHeightForWidth())
        self.comboBox_p5.setSizePolicy(sizePolicy)
        self.comboBox_p5.setObjectName("comboBox_p5")
        self.gridLayout_4.addWidget(self.comboBox_p5, 4, 1, 1, 2)
        self.label_s4 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.label_s4.sizePolicy().hasHeightForWidth())
        self.label_s4.setSizePolicy(sizePolicy)
        self.label_s4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_s4.setObjectName("label_s4")
        self.gridLayout_4.addWidget(self.label_s4, 11, 0, 1, 1)
        self.label_p2 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.label_p2.sizePolicy().hasHeightForWidth())
        self.label_p2.setSizePolicy(sizePolicy)
        self.label_p2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_p2.setObjectName("label_p2")
        self.gridLayout_4.addWidget(self.label_p2, 1, 0, 1, 1)
        self.label_s2 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.label_s2.sizePolicy().hasHeightForWidth())
        self.label_s2.setSizePolicy(sizePolicy)
        self.label_s2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_s2.setObjectName("label_s2")
        self.gridLayout_4.addWidget(self.label_s2, 9, 0, 1, 1)
        self.comboBox_p8 = QtWidgets.QComboBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.comboBox_p8.sizePolicy().hasHeightForWidth())
        self.comboBox_p8.setSizePolicy(sizePolicy)
        self.comboBox_p8.setObjectName("comboBox_p8")
        self.gridLayout_4.addWidget(self.comboBox_p8, 7, 1, 1, 2)
        self.label_p7 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.label_p7.sizePolicy().hasHeightForWidth())
        self.label_p7.setSizePolicy(sizePolicy)
        self.label_p7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_p7.setObjectName("label_p7")
        self.gridLayout_4.addWidget(self.label_p7, 6, 0, 1, 1)
        self.comboBox_p1 = QtWidgets.QComboBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.comboBox_p1.sizePolicy().hasHeightForWidth())
        self.comboBox_p1.setSizePolicy(sizePolicy)
        self.comboBox_p1.setObjectName("comboBox_p1")
        self.gridLayout_4.addWidget(self.comboBox_p1, 0, 1, 1, 2)
        self.label_s7 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.label_s7.sizePolicy().hasHeightForWidth())
        self.label_s7.setSizePolicy(sizePolicy)
        self.label_s7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_s7.setObjectName("label_s7")
        self.gridLayout_4.addWidget(self.label_s7, 14, 0, 1, 1)
        self.comboBox_p2 = QtWidgets.QComboBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.comboBox_p2.sizePolicy().hasHeightForWidth())
        self.comboBox_p2.setSizePolicy(sizePolicy)
        self.comboBox_p2.setObjectName("comboBox_p2")
        self.gridLayout_4.addWidget(self.comboBox_p2, 1, 1, 1, 2)
        self.lineEdit_s1 = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.lineEdit_s1.sizePolicy().hasHeightForWidth())
        self.lineEdit_s1.setSizePolicy(sizePolicy)
        self.lineEdit_s1.setObjectName("lineEdit_s1")
        self.gridLayout_4.addWidget(self.lineEdit_s1, 8, 1, 1, 2)
        self.comboBox_p6 = QtWidgets.QComboBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.comboBox_p6.sizePolicy().hasHeightForWidth())
        self.comboBox_p6.setSizePolicy(sizePolicy)
        self.comboBox_p6.setObjectName("comboBox_p6")
        self.gridLayout_4.addWidget(self.comboBox_p6, 5, 1, 1, 2)
        self.label_s6 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.label_s6.sizePolicy().hasHeightForWidth())
        self.label_s6.setSizePolicy(sizePolicy)
        self.label_s6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_s6.setObjectName("label_s6")
        self.gridLayout_4.addWidget(self.label_s6, 13, 0, 1, 1)
        self.lineEdit_s2 = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.lineEdit_s2.sizePolicy().hasHeightForWidth())
        self.lineEdit_s2.setSizePolicy(sizePolicy)
        self.lineEdit_s2.setObjectName("lineEdit_s2")
        self.gridLayout_4.addWidget(self.lineEdit_s2, 9, 1, 1, 2)
        self.lineEdit_s5 = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.lineEdit_s5.sizePolicy().hasHeightForWidth())
        self.lineEdit_s5.setSizePolicy(sizePolicy)
        self.lineEdit_s5.setObjectName("lineEdit_s5")
        self.gridLayout_4.addWidget(self.lineEdit_s5, 12, 1, 1, 2)
        self.comboBox_p3 = QtWidgets.QComboBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.comboBox_p3.sizePolicy().hasHeightForWidth())
        self.comboBox_p3.setSizePolicy(sizePolicy)
        self.comboBox_p3.setObjectName("comboBox_p3")
        self.gridLayout_4.addWidget(self.comboBox_p3, 2, 1, 1, 2)
        self.label_p5 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.label_p5.sizePolicy().hasHeightForWidth())
        self.label_p5.setSizePolicy(sizePolicy)
        self.label_p5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_p5.setObjectName("label_p5")
        self.gridLayout_4.addWidget(self.label_p5, 4, 0, 1, 1)
        self.label_p6 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.label_p6.sizePolicy().hasHeightForWidth())
        self.label_p6.setSizePolicy(sizePolicy)
        self.label_p6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_p6.setObjectName("label_p6")
        self.gridLayout_4.addWidget(self.label_p6, 5, 0, 1, 1)
        self.label_p3 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.label_p3.sizePolicy().hasHeightForWidth())
        self.label_p3.setSizePolicy(sizePolicy)
        self.label_p3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_p3.setObjectName("label_p3")
        self.gridLayout_4.addWidget(self.label_p3, 2, 0, 1, 1)
        self.comboBox_p4 = QtWidgets.QComboBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.comboBox_p4.sizePolicy().hasHeightForWidth())
        self.comboBox_p4.setSizePolicy(sizePolicy)
        self.comboBox_p4.setObjectName("comboBox_p4")
        self.gridLayout_4.addWidget(self.comboBox_p4, 3, 1, 1, 2)
        self.label_s3 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.label_s3.sizePolicy().hasHeightForWidth())
        self.label_s3.setSizePolicy(sizePolicy)
        self.label_s3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_s3.setObjectName("label_s3")
        self.gridLayout_4.addWidget(self.label_s3, 10, 0, 1, 1)
        self.lineEdit_s6 = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.lineEdit_s6.sizePolicy().hasHeightForWidth())
        self.lineEdit_s6.setSizePolicy(sizePolicy)
        self.lineEdit_s6.setObjectName("lineEdit_s6")
        self.gridLayout_4.addWidget(self.lineEdit_s6, 13, 1, 1, 2)
        self.label_p1 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.label_p1.sizePolicy().hasHeightForWidth())
        self.label_p1.setSizePolicy(sizePolicy)
        self.label_p1.setAlignment(QtCore.Qt.AlignCenter)
        self.label_p1.setObjectName("label_p1")
        self.gridLayout_4.addWidget(self.label_p1, 0, 0, 1, 1)
        self.label_s5 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.label_s5.sizePolicy().hasHeightForWidth())
        self.label_s5.setSizePolicy(sizePolicy)
        self.label_s5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_s5.setObjectName("label_s5")
        self.gridLayout_4.addWidget(self.label_s5, 12, 0, 1, 1)
        self.lineEdit_s7 = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.lineEdit_s7.sizePolicy().hasHeightForWidth())
        self.lineEdit_s7.setSizePolicy(sizePolicy)
        self.lineEdit_s7.setObjectName("lineEdit_s7")
        self.gridLayout_4.addWidget(self.lineEdit_s7, 14, 1, 1, 2)
        self.label_p4 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.label_p4.sizePolicy().hasHeightForWidth())
        self.label_p4.setSizePolicy(sizePolicy)
        self.label_p4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_p4.setObjectName("label_p4")
        self.gridLayout_4.addWidget(self.label_p4, 3, 0, 1, 1)
        self.label_s8 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.label_s8.sizePolicy().hasHeightForWidth())
        self.label_s8.setSizePolicy(sizePolicy)
        self.label_s8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_s8.setObjectName("label_s8")
        self.gridLayout_4.addWidget(self.label_s8, 15, 0, 1, 1)
        self.lineEdit_s8 = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.lineEdit_s8.sizePolicy().hasHeightForWidth())
        self.lineEdit_s8.setSizePolicy(sizePolicy)
        self.lineEdit_s8.setObjectName("lineEdit_s8")
        self.gridLayout_4.addWidget(self.lineEdit_s8, 15, 1, 1, 2)
        self.gridLayout_5.addLayout(self.gridLayout_4, 2, 4, 5, 1)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setObjectName("pushButton_2")
        self.gridLayout_2.addWidget(self.pushButton_2, 1, 0, 1, 1)
        self.listView_2 = QtWidgets.QListView(self.centralwidget)
        self.listView_2.setObjectName("listView_2")
        self.gridLayout_2.addWidget(self.listView_2, 1, 1, 1, 1)
        self.label_l2 = QtWidgets.QLabel(self.centralwidget)
        self.label_l2.setObjectName("label_l2")
        self.gridLayout_2.addWidget(self.label_l2, 0, 1, 1, 1)
        self.gridLayout_5.addLayout(self.gridLayout_2, 3, 2, 1, 2)
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_l3 = QtWidgets.QLabel(self.centralwidget)
        self.label_l3.setObjectName("label_l3")
        self.gridLayout_3.addWidget(self.label_l3, 0, 1, 1, 1)
        self.listView_3 = QtWidgets.QListView(self.centralwidget)
        self.listView_3.setObjectName("listView_3")
        self.gridLayout_3.addWidget(self.listView_3, 1, 1, 1, 1)
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setObjectName("pushButton_3")
        self.gridLayout_3.addWidget(self.pushButton_3, 1, 0, 1, 1)
        self.gridLayout_5.addLayout(self.gridLayout_3, 4, 2, 1, 2)
        self.gridLayout_6 = QtWidgets.QGridLayout()
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.label_l4 = QtWidgets.QLabel(self.centralwidget)
        self.label_l4.setObjectName("label_l4")
        self.gridLayout_6.addWidget(self.label_l4, 0, 1, 1, 1)
        self.pushButton_4 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_4.setObjectName("pushButton_4")
        self.gridLayout_6.addWidget(self.pushButton_4, 1, 0, 1, 1)
        self.listView_4 = QtWidgets.QListView(self.centralwidget)
        self.listView_4.setObjectName("listView_4")
        self.gridLayout_6.addWidget(self.listView_4, 1, 1, 1, 1)
        self.gridLayout_5.addLayout(self.gridLayout_6, 5, 2, 1, 2)
        self.gridLayout_7 = QtWidgets.QGridLayout()
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.label_l5 = QtWidgets.QLabel(self.centralwidget)
        self.label_l5.setObjectName("label_l5")
        self.gridLayout_7.addWidget(self.label_l5, 0, 1, 1, 1)
        self.listView_5 = QtWidgets.QListView(self.centralwidget)
        self.listView_5.setEnabled(True)
        self.listView_5.setObjectName("listView_5")
        self.gridLayout_7.addWidget(self.listView_5, 1, 1, 1, 1)
        self.pushButton_5 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_5.setObjectName("pushButton_5")
        self.gridLayout_7.addWidget(self.pushButton_5, 1, 0, 1, 1)
        self.gridLayout_5.addLayout(self.gridLayout_7, 6, 2, 1, 2)
        self.label_method = QtWidgets.QLabel(self.centralwidget)
        self.label_method.setAlignment(QtCore.Qt.AlignCenter)
        self.label_method.setObjectName("label_method")
        self.gridLayout_5.addWidget(self.label_method, 0, 3, 1, 2)
        self.setWidget(self.centralwidget)

        self.retranslateUi()

    def retranslateUi(self):
        _translate = QtCore.QCoreApplication.translate
        self.label_window.setText(_translate("MainWindow", "数据窗口选择"))
        self.label_database.setText(_translate("MainWindow", "内置数据库选择"))
        self.pushButton_start.setText(_translate("MainWindow", "开始分析"))
        self.pushButton_help.setText(_translate("MainWindow", "显示帮助"))
        self.label_l1.setText(_translate("MainWindow", "变量选择1"))
        self.pushButton_1.setText(_translate("MainWindow", "添加"))
        self.label_p8.setText(_translate("MainWindow", "参数选择"))
        self.label_s1.setText(_translate("MainWindow", "参数设定"))
        self.label_s4.setText(_translate("MainWindow", "参数设定"))
        self.label_p2.setText(_translate("MainWindow", "参数选择"))
        self.label_s2.setText(_translate("MainWindow", "参数设定"))
        self.label_p7.setText(_translate("MainWindow", "参数选择"))
        self.label_s7.setText(_translate("MainWindow", "参数设定"))
        self.label_s6.setText(_translate("MainWindow", "参数设定"))
        self.label_p5.setText(_translate("MainWindow", "参数选择"))
        self.label_p6.setText(_translate("MainWindow", "参数选择"))
        self.label_p3.setText(_translate("MainWindow", "参数选择"))
        self.label_s3.setText(_translate("MainWindow", "参数设定"))
        self.label_p1.setText(_translate("MainWindow", "参数选择"))
        self.label_s5.setText(_translate("MainWindow", "参数设定"))
        self.label_p4.setText(_translate("MainWindow", "参数选择"))
        self.label_s8.setText(_translate("MainWindow", "参数设定"))
        self.pushButton_2.setText(_translate("MainWindow", "添加"))
        self.label_l2.setText(_translate("MainWindow", "变量选择1"))
        self.label_l3.setText(_translate("MainWindow", "变量选择1"))
        self.pushButton_3.setText(_translate("MainWindow", "添加"))
        self.label_l4.setText(_translate("MainWindow", "变量选择1"))
        self.pushButton_4.setText(_translate("MainWindow", "添加"))
        self.label_l5.setText(_translate("MainWindow", "变量选择1"))
        self.pushButton_5.setText(_translate("MainWindow", "添加"))
        self.label_method.setText(_translate("MainWindow", "TextLabel"))

    def adjustCount(self):
        SubWindow_Pingouin_basic.count += 1